name: supermarket_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  banner_carousel: ^1.2.1
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  connectivity_plus: ^3.0.3
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_secure_storage: ^8.0.0
  dartz: ^0.10.1
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  flutter_typeahead: ^4.3.6
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.4
  cool_alert: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
